baseurl: http://blog.brianz.bz/
title: Brian Z
theme: "ghostwriter"
languageCode: en-us
googleAnalytics: UA-75475240-1
disqusShortname: brianz
copyright: "&copy; 2016-2017. All rights reserved."

canonifyurls: true
paginate: 10

blackfriday:
  hrefTargetBlank: true

indexes:
  tag: tags
  topic: topics

author: 
  name: Brian Zambrano

params:
  intro: true
  headline: Brian Z
  description: >
      A SAAS application architecture blog. Current topics include Docker, Python microservices, 
      Serverless and (coming soon) Elixir.
  dateFormat: 02 Jan 2006, 15:04
  highlightJsLocalUrl: js/highlight.pack.js

  twitter: https://twitter.com/brianzambrano
  facebook: brian.zambrano
  instagram: bzambrano
  linkedin: https://www.linkedin.com/in/brianzambrano
  hackernews: https://news.ycombinator.com/user?id=bezeee
  github: https://github.com/brianz
  stackoverflow: http://stackoverflow.com/users/87858/brianz


# Shown in the side menu.
menu:
  main:
    - name: Home
      weight: 0
      identifier: home
      url: /
    - name: About
      weight: 2
      identifier: about
      url: /about/
    - name: Posts
      weight: 2
      identifier: post
      url: /post/
